const GET_TODOS = 'GET_TODOS';
const START_FETCHING = 'START_FETCHING';
const STOP_FETCHING = 'STOP_FETCHING';
const REMOVE_TODO = 'REMOVE_TODO';
const CHANGE_ALERT_STATE = 'CHANGE_ALERT_STATE';

export { GET_TODOS, START_FETCHING, STOP_FETCHING, REMOVE_TODO, CHANGE_ALERT_STATE };
